name: Generate GitHub Streak Image

on:
  schedule:
    - cron: "0 0 * * *"  # daily at midnight UTC
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download streak image
        run: |
          curl -o streak.svg "https://github-readme-streak-stats.herokuapp.com/?user=abufarisdev&theme=radical"

      - name: Commit streak image
        run: |
          git config --local user.email "abufariskolkata@example.com"
          git config --local user.name "Abu Faris"
          git add streak.svg
          git commit -m "Update GitHub streak image" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/abufarisdev/abufarisdev.git HEAD:main
