name: Update GitHub Streak Stats

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight UTC
  workflow_dispatch:      # Allow manual triggering

jobs:
  update-streak:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Generate streak SVG
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          python scripts/generate_streak_advanced.py

      - name: Commit and push changes
        run: |
          git config --local user.email "abufariskolkata@gmail.com"
          git config --local user.name "GitHub Actions"
          git add streak.svg
          git commit -m "Update streak stats - $(date +'%Y-%m-%d')" || exit 0
          git push
