name: Generate GitHub Streak Image

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install streak generator
        run: npm install -g github-readme-streak-stats

      - name: Generate streak image
        run: |
          github-readme-streak-stats \
            --user abufarisdev \
            --theme radical \
            --hide-border \
            --output streak.svg

      - name: Commit streak image
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add streak.svg
          git commit -m "Update GitHub streak image" || echo "No changes to commit"
          git push
